### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by anikethsaha** [anikethsaha/MERN-Boilerplate#61]
Will create a better explaining proposal soon

## V1 (next)

**List of things need for `v1`**

- [ ] Plugins support : gatsby like integration with the core
- [ ] Fully automated docs
- [ ] Better Tests
  - [ ] Server
- [ ] CLI

Need to work in `next` branch. Not in master

## Support

- [ ] CI
  - [ ] codesandbox https://github.com/anikethsaha/mern/issues/127
  - [ ] lighthouse https://github.com/anikethsaha/mern/issues/125

Feel free to add more if needed ...

Thanks

**Comment by anikethsaha** [comment]
@przemwierzbicki @anmol5varma as far as this roadmap is concerned, I would appreciate your comments in this. 
And Also do we need more tests for the client? For me, I guess the current tests are fine. 
I just need to add some for the server. I will try to cover that too soon and will appreciate your help too. 😃

**Comment by wincentrtz** [comment]
Hello @anikethsaha 

I'm currently working on a project about project structure especially with React.
Do you have any problem with ur current project structure?
Maybe we can have a discussion about it :)

**Comment by anikethsaha** [comment]
for project structure, I actually had suggestion like removing the `src/common` folder,  
Actually, when I started the project, I  thought of doing SSR for every component, not based on the route 
But I don't think that gonna be effective. Although I can reconsider that if I find any better reason !

You can check the v1 https://github.com/anikethsaha/MERN/pull/117

**Comment by anikethsaha** [comment]
yeah do ping me on twitter. We can consider that for v1 or if possible v2.

**Comment by wincentrtz** [comment]
Actually I'm not using twitter. :(
can we try using LinkedIn or other?

**Comment by anikethsaha** [comment]
yeah sure 
https://www.linkedin.com/in/aniketh-saha-8a67aa148/

**Comment by devcer** [comment]
I can help with writing unit tests. which file should I start with?

**Comment by anikethsaha** [comment]
Thanks, That's great. 
Actually, for frontend, it seems that we convered most of the part, Can you try for the server?
